services:
  service-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backparkontrol:latest
    container_name: backend
    ports:
      - "7500:7500"
    networks:
      - redparkontrol
    environment:
      - SUPABASE_DB_URL=postgresql://postgres.lngtnhmyehqqjmavffqq:parkontrol123@aws-0-us-west-2.pooler.supabase.com:6543/postgres
      - PORT=7500
      - JWT_SECRET=parkontrol_dev_secret_2026
      - DB_SYNC=false

  service-frontend:
    build:
        context: ./frontend-angular
        dockerfile: Dockerfile
    image: frontparkontrol:latest
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - service-backend
    networks:
      - redparkontrol

networks:
  redparkontrol:
    driver: bridge
