# ---------- STAGE 1: build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Build del proyecto (NestJSAngular → dist/)
RUN npm run build


# ---------- STAGE 2: producción ----------
FROM node:20-alpine

WORKDIR /app

# Copiar solo lo necesario
COPY package*.json ./

# Instalar solo dependencias de producción
RUN npm install --omit=dev

# Copiar build desde builder
COPY --from=builder /app/dist ./dist

# Puerto (ajústalo si usas otro)
EXPOSE 3000

# Comando de inicio
CMD ["node", "dist/src/main.js"]