
sonar.projectKey=backend-parkontrol
sonar.projectName=Parkontrol Backend
sonar.projectVersion=1.0.2
sonar.host.url=http://localhost:9000
sonar.qualityprofile.name=Sonar way

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/test/**/*.ts,**/tests/**/*.ts
sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**,**/*.spec.ts,**/jest.config.ts

sonar.coverage.exclusions=**/*.spec.ts,**/test/**,**/tests/**,**/dist/**,**/node_modules/**,**/coverage/**,**/controller/**,**/entities/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.token=sqa_305cc7ac562921b10b437605daf6cce4d9382e4e
