sonar.projectKey=backend-parkontrol
sonar.projectName=Parkontrol Backend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/test/**/*.ts
sonar.exclusions=**/*.spec.ts,**/dist/**,**/node_modules/**,**/coverage/**,**/auth/**,**/celdas/**,**/empresas/**,**/parqueaderos/**,**/reportes/**,**/seeds/**,**/shared/**,**/tarifas/**,**/usuarios/**,**/vehiculos/**,**/vistas/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.login=sqa_f3ff5b662bcde24baab8f092f60fa6454b96306a
