FROM node:20-alpine 

WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar código
COPY . .

EXPOSE 4200
# Comando de inicio
CMD ["npm","run","start"]